import { Injectable, Logger, Optional } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { InjectQueue } from '@nestjs/bullmq';
import { Queue } from 'bullmq';
import { Resend } from 'resend';
import * as Sentry from '@sentry/nestjs';
import { PrismaService } from '../prisma/prisma.service';
import { EMAIL_QUEUE_NAME, EmailJobData } from './email.types';

/**
 * Low-level email delivery mechanics: the Resend client, the RGPD unsubscribe
 * footer / opt-out check, and the BullMQ-backed async delivery queue.
 *
 * This service owns no notification-domain logic (in-app notifications,
 * preferences, templates) — it only knows how to actually get an HTML email
 * out the door, synchronously or via the queue. Callers (e.g. NotificationsService)
 * are responsible for building the HTML and deciding whether a given email
 * should be sent at all (preference gating).
 *
 * Extracted from NotificationsService to break a circular module dependency:
 * previously NotificationsModule needed EmailQueueModule (to enqueue) and
 * EmailQueueModule needed NotificationsModule (the processor called back into
 * NotificationsService.sendEmailDirect), forcing forwardRef() on both sides.
 * EmailService has no dependency on the notifications module at all, so both
 * NotificationsModule and the queue processor can depend on it directly.
 */
@Injectable()
export class EmailService {
  private readonly logger = new Logger(EmailService.name);
  private readonly resend?: Resend;
  private readonly fromEmail?: string;

  constructor(
    private readonly configService: ConfigService,
    private readonly prisma: PrismaService,
    @Optional() @InjectQueue(EMAIL_QUEUE_NAME) private readonly emailQueue?: Queue,
  ) {
    const apiKey = this.configService.get<string>('RESEND_API_KEY');
    this.fromEmail = this.configService.get<string>('RESEND_FROM_EMAIL');

    if (apiKey) {
      this.resend = new Resend(apiKey);
    } else {
      this.logger.warn('RESEND_API_KEY not configured — email notifications are disabled');
    }

    if (!this.fromEmail) {
      this.logger.warn('RESEND_FROM_EMAIL not configured — email notifications may fail');
    }
  }

  /** Returns true when the email client is ready to send. */
  hasEmailClient(): boolean {
    return Boolean(this.resend && this.fromEmail);
  }

  /**
   * Low-level email sender — throws on delivery failure.
   *
   * When `skipUnsubscribeFooter` is false (default) this method:
   *  1. Looks up the recipient to check their opt-out preference — returns early if opted out.
   *  2. Appends a RGPD-compliant unsubscribe footer using the user's permanent token.
   *
   * Pass `skipUnsubscribeFooter = true` for critical transactional emails (verification,
   * password reset) that must always be delivered regardless of marketing preferences.
   *
   * Errors are NOT swallowed — callers decide whether to await (critical) or fire-and-forget (non-critical).
   */
  async sendEmail(
    to: string,
    subject: string,
    html: string,
    skipUnsubscribeFooter = false,
  ): Promise<void> {
    // Never send to test/example addresses — generated by automated tests, must never hit Resend
    if (/@example\.com$/i.test(to) || /@test\.local$/i.test(to)) {
      this.logger.debug(`[mock] Skipping email to test address: ${to} — ${subject}`);
      return;
    }

    if (!this.resend || !this.fromEmail) {
      this.logger.warn(`[mock] Email client not configured — skipping email to ${to}: ${subject}`);
      return;
    }

    let finalHtml = html;

    if (!skipUnsubscribeFooter) {
      const user = await this.prisma.user
        .findUnique({
          where: { email: to },
          select: { emailOptOut: true, emailUnsubscribeToken: true },
        })
        .catch(() => null);

      if (user?.emailOptOut) return; // silently skip — user opted out

      if (user?.emailUnsubscribeToken) {
        const frontendUrl = this.configService.get<string>('FRONTEND_URL') ?? '';
        finalHtml += `
          <hr style="margin:40px 0;border:none;border-top:1px solid #eee">
          <p style="color:#888;font-size:12px;text-align:center">
            Vous recevez cet email car vous êtes inscrit sur SouthConnect.<br>
            <a href="${frontendUrl}/unsubscribe?token=${user.emailUnsubscribeToken}"
               style="color:#aaa;text-decoration:underline">
              Se désabonner des emails
            </a>
          </p>
        `;
      }
    }

    // Abort if Resend stalls — throws so callers can retry.
    // The Resend SDK resolves the promise even on API errors (returns { data: null, error: {...} })
    // so we must inspect the result and throw explicitly to surface failures.
    const send = this.resend.emails.send({ from: this.fromEmail, to, subject, html: finalHtml });
    let timeoutId: ReturnType<typeof setTimeout>;
    const timeout = new Promise<never>((_, reject) => {
      timeoutId = setTimeout(() => reject(new Error('Resend timeout after 10 s')), 10_000);
    });
    const result = await Promise.race([send, timeout]).finally(() => clearTimeout(timeoutId!));
    if (result.error) {
      throw new Error(`Resend ${result.error.statusCode}: ${result.error.message}`);
    }
  }

  /**
   * Direct email delivery — called by the BullMQ processor.
   * Delegates to sendEmail. Throws on failure so the processor can re-throw
   * and trigger BullMQ retries.
   */
  async sendEmailDirect(data: EmailJobData): Promise<void> {
    await this.sendEmail(data.to, data.subject, data.html, data.skipUnsubscribeFooter);
  }

  /**
   * Enqueues a non-critical email for asynchronous, persistent delivery via BullMQ.
   *
   * When the BullMQ queue is available the job is persisted in Redis so the email
   * survives a process crash. When the queue is unavailable (e.g. Redis not configured
   * in dev) the method falls back to the legacy in-process retry mechanism.
   *
   * Critical emails (verification, password reset, password changed) bypass this
   * method entirely — callers send them synchronously via sendEmail().
   */
  sendEmailAsync(
    to: string,
    subject: string,
    html: string,
    skipUnsubscribeFooter = false,
    jobType = 'generic',
  ): void {
    // In test mode, skip queueing entirely — no real Redis jobs, no Resend calls
    if (this.configService.get<string>('NODE_ENV') === 'test') {
      this.logger.debug(`[test] Email skipped (not queued): ${to} — ${subject}`);
      return;
    }

    if (this.emailQueue) {
      const jobData: EmailJobData = { to, subject, html, skipUnsubscribeFooter, jobType };
      this.emailQueue.add('send', jobData).catch((err: Error) => {
        this.logger.warn(
          `Failed to enqueue email job [${jobType}] → ${to}: ${err.message}. Falling back to in-process delivery.`,
        );
        // Fallback: deliver in-process if queue.add itself failed
        this.sendEmailFallback(to, subject, html, skipUnsubscribeFooter);
      });
      return;
    }
    // No queue available — use in-process delivery with manual retries
    this.sendEmailFallback(to, subject, html, skipUnsubscribeFooter);
  }

  /**
   * Legacy in-process retry fallback for when BullMQ is unavailable.
   * Retries up to 2 times with linear backoff (2 s, 4 s) before giving up.
   */
  private sendEmailFallback(
    to: string,
    subject: string,
    html: string,
    skipUnsubscribeFooter = false,
  ): void {
    const MAX_RETRIES = 2;
    const attempt = (remaining: number) => {
      this.sendEmail(to, subject, html, skipUnsubscribeFooter).catch((err: Error) => {
        if (remaining > 0) {
          const delayMs = (MAX_RETRIES - remaining + 1) * 2_000; // 2s, 4s
          setTimeout(() => attempt(remaining - 1), delayMs);
        } else {
          this.logger.error(`Email to ${to} failed after all retries: ${err.message}`, err.stack);
          Sentry.captureException(err, { tags: { email_to: to, email_subject: subject } });
        }
      });
    };
    setImmediate(() => attempt(MAX_RETRIES));
  }
}
